### ISSUE TITLE
symbtools import fails

### ISSUE THREAD

**Issue by klim-** [TUD-RST/symbtools#11]
Importing symbtools using python 3.9.1 and sympy 1.7.1 fails and throws
`AttributeError: module 'sympy' has no attribute 'numbers'`.

Edit: If I downgrade sympy to version 1.6.2 the import seems to work. However, there is a warning

`/usr/lib/python3.9/site-packages/sympy/__init__.py:672: SymPyDeprecationWarning:
importing sympy.core.numbers with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.numbers instead. See
https://github.com/sympy/sympy/issues/18245 for more info.`

What I find strange is that [this](https://cloud.drone.io/TUD-RST/symbtools/11/1/2) test seemed to work with python 3.6 and sympy 1.7.1.

**Comment by cknoll** [comment]
I just tried the current main branch with Python 3.9.0 and sympy 1.7.1.

While I get some DeprecationWarnings (w.r.t to np.float and np.complex) there is no AttributeError on my system. Which version/branch did you use?

**Comment by cknoll** [comment]
Probably you experienced a bug which was fixed in https://github.com/TUD-RST/symbtools/commit/c92374633f9fb62526184376b8b04664fc2fdf28. However, version 0.3.1 was not yet on pypi. I just uploaded that release.

**Comment by klim-** [comment]
In fact I was using the outdated pypi-version. With the version 0.3.1 it works as expected. Thanks!
